name: smallbuthandy

on:
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Excerpt
        run: npm run build:exc
